/**
 * Tile 目录（需求 §8）。
 *
 * readiness 字段不是需求文档抄来的，而是按当前 KXC 埋点实证结论标注的：
 * 数据拿不到就如实写 blocked / partial，并把原因显示在 Tile 上，
 * 而不是画一张空图让人误以为"没问题"。
 *
 * 实证依据（worktree @ origin/main）：
 *   - 顶层 op_name 从未被赋值，算子名只在 fields.op_name（src/base/disco/executor.cc:128）
 *   - kernel_exec span 包裹的是 ccl_backend_->Copy，不是真实 kernel 执行（executor.cc:153）
 *   - cache_* span 只有 fields.shape_hash，shape_signature 在父 span（runtime_session.cc:47/57/65/72）
 *   - trace.json 的 args 只有 status/severity/message（profiling.cc:789-793）
 *   - diagnosis.json 的 evidence 无 span/时间引用，C++ 侧甚至只有 4 个字段（profiling.cc:1142-1146）
 */

import type { TileSpec, TileType } from '../state/types'

const SPECS: Record<TileType, TileSpec> = {
  kpi: {
    type: 'kpi',
    title: 'KPI 指标组',
    purpose: '一屏看清编译总耗时、Pass 数、缓存命中率与告警数',
    minWidth: '1/3',
    preferredWidth: '1/3',
    minHeightPx: 120,
    preferredHeightPx: 180,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'component', 'severity', 'search'],
    writes: [],
    readiness: 'ready',
  },
  phase_breakdown: {
    type: 'phase_breakdown',
    title: '阶段耗时分解',
    purpose: '编译时间花在 Relay、Lowering、TIR、CodeGen 哪一段',
    minWidth: '1/3',
    preferredWidth: '1/2',
    minHeightPx: 180,
    preferredHeightPx: 260,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'search'],
    writes: ['component'],
    readiness: 'ready',
  },
  hotspot_topn: {
    type: 'hotspot_topn',
    title: 'Hotspot Top-N',
    purpose: '按 Pass / 算子 / Kernel 排出最耗时的对象',
    minWidth: '1/3',
    preferredWidth: '1/3',
    minHeightPx: 200,
    preferredHeightPx: 300,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'component', 'search'],
    writes: ['pass', 'op', 'kernel'],
    readiness: 'partial',
    readinessNote:
      'Pass 维度数据完整可用；算子维度取自 execution_plan.kernel_exec span，而该 span 当前包裹的是值拷贝而非真实 kernel 执行，只能用于结构分析',
  },
  perfetto_timeline: {
    type: 'perfetto_timeline',
    title: 'Timeline',
    purpose: '按时间轴查看事件分布，框选时间范围联动其他图',
    minWidth: '2/3',
    preferredWidth: 'full',
    minHeightPx: 260,
    preferredHeightPx: 420,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: true,
    reads: ['bundleId', 'runId', 'timeRange', 'component', 'severity', 'search'],
    writes: ['timeRange', 'component'],
    readiness: 'partial',
    readinessNote:
      '内置时间线可用；嵌入 Perfetto 后无法从选中事件回跳，因为 trace.json 的 args 只有 status/severity/message，不含 run_id/span_id',
  },
  pass_waterfall: {
    type: 'pass_waterfall',
    title: 'Pass Waterfall',
    purpose: '按执行顺序看每个 Pass 的耗时与 IR 体积变化',
    minWidth: '1/2',
    preferredWidth: '2/3',
    minHeightPx: 240,
    preferredHeightPx: 380,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'pass', 'component', 'search'],
    writes: ['pass', 'timeRange'],
    readiness: 'ready',
  },
  pass_ranking: {
    type: 'pass_ranking',
    title: 'Pass 耗时排行',
    purpose: '找出最慢的 Pass 以及它是否真的改动了 IR',
    minWidth: '1/3',
    preferredWidth: '1/3',
    minHeightPx: 200,
    preferredHeightPx: 320,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'component', 'search'],
    writes: ['pass'],
    readiness: 'ready',
  },
  shape_cache_heatmap: {
    type: 'shape_cache_heatmap',
    title: 'Shape × Cache 热力图',
    purpose: '哪些输入 shape 反复未命中缓存、触发同步编译',
    minWidth: '1/2',
    preferredWidth: '1/2',
    minHeightPx: 220,
    preferredHeightPx: 320,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'shapeSignature', 'search'],
    writes: ['shapeSignature'],
    readiness: 'ready',
    readinessNote:
      'shape 签名由 shape_hash 与父 span 联查补全（cache_* span 本身不带 shape_signature），无需改动 C++',
  },
  kernel_duration_dist: {
    type: 'kernel_duration_dist',
    title: 'Kernel 耗时分布',
    purpose: '看 kernel 耗时的分布形态与长尾',
    minWidth: '1/3',
    preferredWidth: '1/2',
    minHeightPx: 200,
    preferredHeightPx: 300,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'kernel', 'device', 'search'],
    writes: ['kernel'],
    readiness: 'partial',
    readinessNote: '无 CUPTI 时只有逻辑执行耗时，不是 GPU 硬件耗时',
  },
  kernel_topn: {
    type: 'kernel_topn',
    title: 'Kernel Top-N',
    purpose: '最耗时的 kernel 排行',
    minWidth: '1/3',
    preferredWidth: '1/3',
    minHeightPx: 200,
    preferredHeightPx: 300,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'device', 'search'],
    writes: ['kernel'],
    readiness: 'partial',
    readinessNote: 'CPU 路径下 kernel_symbol 多为空，需要 CUPTI 才有完整硬件 kernel 数据',
  },
  diagnostics: {
    type: 'diagnostics',
    title: '诊断',
    purpose: '查看自动诊断结论、证据与下一步建议',
    minWidth: '1/3',
    preferredWidth: '1/3',
    minHeightPx: 200,
    preferredHeightPx: 340,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'severity', 'component', 'search'],
    writes: ['pass', 'component', 'severity'],
    readiness: 'partial',
    readinessNote:
      'evidence 只有标量与文本，没有 span_id 或时间范围，因此证据只能按 pass/component 名字近似回跳，无法精确定位到事件；未跑 analyze_bundle 时只有占位诊断',
  },
  regression_delta: {
    type: 'regression_delta',
    title: '回归对比',
    purpose: 'Baseline 与 Candidate 的逐 Pass 耗时差异',
    minWidth: '1/3',
    preferredWidth: '1/2',
    minHeightPx: 220,
    preferredHeightPx: 340,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: false,
    reads: ['bundleId', 'baselineBundleId', 'runId', 'timeRange', 'search'],
    writes: ['pass'],
    readiness: 'partial',
    readinessNote:
      'Pass 维度可按名字自动对齐；算子与 Kernel 维度因 op_name/kernel_symbol 未填充而无法对齐',
  },
  logs: {
    type: 'logs',
    title: '日志',
    purpose: '按级别查看编译期日志与告警',
    minWidth: '1/3',
    preferredWidth: '1/2',
    minHeightPx: 180,
    preferredHeightPx: 300,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: false,
    heavy: false,
    reads: ['bundleId', 'runId', 'timeRange', 'component', 'severity', 'search'],
    writes: ['severity', 'component'],
    readiness: 'ready',
  },
  event_table: {
    type: 'event_table',
    title: '事件表',
    purpose: '按当前过滤条件浏览原始事件',
    minWidth: '1/2',
    preferredWidth: '2/3',
    minHeightPx: 240,
    preferredHeightPx: 420,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: true,
    heavy: true,
    reads: [
      'bundleId',
      'runId',
      'timeRange',
      'component',
      'eventType',
      'device',
      'workerId',
      'op',
      'pass',
      'kernel',
      'shapeSignature',
      'status',
      'severity',
      'search',
    ],
    writes: ['component', 'eventType', 'pass', 'op', 'kernel', 'device', 'severity'],
    readiness: 'ready',
  },
  ir_diff: {
    type: 'ir_diff',
    title: 'IR Before/After',
    purpose: '对照某个 Pass 前后的 IR 文本',
    minWidth: '1/2',
    preferredWidth: '2/3',
    minHeightPx: 280,
    preferredHeightPx: 460,
    stackable: true,
    tabbable: true,
    gatherable: true,
    comparable: false,
    heavy: true,
    reads: ['bundleId', 'runId', 'pass'],
    writes: [],
    readiness: 'partial',
    readinessNote:
      'artifact 存在时可用；从 URL 加载的 bundle 需按需拉取 artifact，目录来源才会预读',
  },
}

export function getTileSpec(type: TileType): TileSpec {
  return SPECS[type]
}

export const ALL_TILE_SPECS: readonly TileSpec[] = Object.values(SPECS)

/** MVP 验收要求的 P0 图表（§22 第 12–19 项）。 */
export const MVP_TILE_TYPES: readonly TileType[] = [
  'kpi',
  'phase_breakdown',
  'hotspot_topn',
  'pass_waterfall',
  'shape_cache_heatmap',
  'diagnostics',
  'event_table',
  'perfetto_timeline',
]

/** 重型 Tile 同时活动上限（§18.4）。 */
export const MAX_ACTIVE_HEAVY_TILES = 3
