#!/usr/bin/env python3
"""Generate critical OperatorSpec metadata from contracts/relay_op_contract.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render(contract: dict[str, Any]) -> str:
    effect = {
        "pure": "OperatorEffectKind::kPure",
        "stateful": "OperatorEffectKind::kStateful",
        "device_communication": "OperatorEffectKind::kDeviceCommunication",
    }
    lowering = {
        "none": "OperatorLoweringKind::kNone",
        "single": "OperatorLoweringKind::kSingleTE",
        "multi": "OperatorLoweringKind::kMultiTE",
        "exec_plan": "OperatorLoweringKind::kExecPlan",
    }
    lines = [
        "// Generated by python/tools/generate_relay_op_contract.py; do not edit.",
        "#pragma once",
        "",
        "#include <stdexcept>",
        "#include <string>",
        "",
        '#include "kxc/relay/op.h"',
        "",
        "namespace kxc::relay::op_contract_generated {",
        "",
        f"inline constexpr int kContractVersion = {int(contract['version'])};",
        "",
        "inline OperatorSpec Spec(const std::string& name) {",
    ]
    for name, op in contract["operators"].items():
        lines.extend(
            [
                f"    if (name == {q(name)}) {{",
                "        OperatorSpec spec;",
                f"        spec.name = {q(name)};",
                f"        spec.schema_version = {int(op['schema_version'])};",
                f"        spec.category = {q(op['category'])};",
                f"        spec.input_arity.num_inputs = {int(op['num_inputs'])};",
                f"        spec.input_arity.min_inputs = {int(op.get('min_inputs', -1))};",
                f"        spec.input_arity.max_inputs = {int(op.get('max_inputs', -1))};",
                f"        spec.attrs_type_key = {q(op['attrs'] or '')};",
                f"        spec.output_arity = {int(op['output_arity'])};",
                f"        spec.type_relation_key = {q(op['type_relation_key'])};",
                f"        spec.effect = {effect[op['effect']]};",
                f"        spec.deterministic = {'true' if op['deterministic'] else 'false'};",
                f"        spec.alias_contract = {q(op['alias'])};",
                f"        spec.lowering_kind = {lowering[op['lowering']]};",
                f"        spec.lowering_key = {q(op['lowering_key'])};",
                "        return spec;",
                "    }",
            ]
        )
    lines.extend(
        [
            '    throw std::invalid_argument("operator is absent from generated contract: " + name);',
            "}",
            "",
            "}  // namespace kxc::relay::op_contract_generated",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--matrix", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    matrix = Path(args.matrix)
    output = Path(args.output)
    generated = render(json.loads(matrix.read_text(encoding="utf-8")))
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != generated:
            print(f"generated Relay op contract is stale: {output}")
            return 1
        print(f"generated Relay op contract is current: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
