#!/usr/bin/env python3
"""Generate the C++ PassSpec contract from contracts/pass_contract.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def cpp_array(values: list[str]) -> str:
    if not values:
        return "{}"
    return "{" + ", ".join(f"String({cpp_string(value)})" for value in values) + "}"


def render(contract: dict[str, Any]) -> str:
    defaults = contract.get("pass_defaults", {})
    repeatable_passes = contract.get("rules", {}).get("repeatable_passes", [])
    lines = [
        "// Generated by python/tools/generate_pass_contract.py; do not edit.",
        "#pragma once",
        "",
        "#include <stdexcept>",
        "#include <string>",
        "#include <utility>",
        "#include <vector>",
        "",
        '#include "kxc/pass/pass.h"',
        "",
        "namespace kxc::pass_contract_generated {",
        "",
        f"inline constexpr int kContractVersion = {int(contract['version'])};",
        "",
        "inline const std::vector<PassSpec>& Specs() {",
        "    static const std::vector<PassSpec> specs = [] {",
        "        std::vector<PassSpec> result;",
    ]
    for key, raw in contract["passes"].items():
        spec = {**defaults, **raw}
        lines.extend(
            [
                "        {",
                "            PassSpec spec;",
                f"            spec.name = String({cpp_string(spec['name'])});",
                f"            spec.schema_version = {int(spec['schema_version'])};",
                f"            spec.dialect = ParseIRDialect({cpp_string(spec['dialect'])});",
                f"            spec.scope = ParsePassScope({cpp_string(spec['scope'])});",
                f"            spec.phase = String({cpp_string(spec['phase'])});",
                f"            spec.opt_level = {int(spec['opt_level'])};",
                f"            spec.required_invariants = {cpp_array(spec['required_invariants'])};",
                f"            spec.produced_invariants = {cpp_array(spec['produced_invariants'])};",
                f"            spec.declarative_only_invariants = {cpp_array(spec['declarative_only_invariants'])};",
                f"            spec.preserved_analyses = {cpp_array(spec['preserved_analyses'])};",
                f"            spec.invalidated_analyses = {cpp_array(spec['invalidated_analyses'])};",
                f"            spec.supported_control_capabilities = {cpp_array(spec['supported_control_capabilities'])};",
                f"            spec.target_requirements = {cpp_array(spec['target_requirements'])};",
                f"            spec.may_change_ir = {'true' if spec['may_change_ir'] else 'false'};",
                f"            spec.deterministic = {'true' if spec['deterministic'] else 'false'};",
                f"            spec.idempotent = {'true' if spec['idempotent'] else 'false'};",
                f"            spec.thread_safe = {'true' if spec['thread_safe'] else 'false'};",
                f"            spec.implementation_key = String({cpp_string(spec['implementation_key'])});",
                "            result.push_back(std::move(spec));",
                "        }",
            ]
        )
    lines.extend(
        [
            "        return result;",
            "    }();",
            "    return specs;",
            "}",
            "",
            "inline Array<PassSpec> Specs(IRDialect dialect) {",
            "    Array<PassSpec> result;",
            "    for (const PassSpec& spec : Specs()) {",
            "        if (spec.dialect == dialect) result.push_back(spec);",
            "    }",
            "    return result;",
            "}",
            "",
            "inline bool IsRepeatable(IRDialect dialect, const std::string& name) {",
        ]
    )
    for key in repeatable_passes:
        dialect, pass_name = key.split(".", 1)
        lines.append(
            f"    if (dialect == ParseIRDialect({cpp_string(dialect)}) && "
            f"name == {cpp_string(pass_name)}) return true;"
        )
    lines.extend(
        [
            "    return false;",
            "}",
            "",
            "inline Array<String> Pipeline(const std::string& name) {",
        ]
    )
    for name, passes in contract["pipelines"].items():
        lines.append(f"    if (name == {cpp_string(name)}) return {cpp_array(passes)};")
    lines.extend(
        [
            '    throw std::invalid_argument("unknown generated pipeline: " + name);',
            "}",
            "",
            "}  // namespace kxc::pass_contract_generated",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--matrix", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    matrix = Path(args.matrix)
    output = Path(args.output)
    contract = json.loads(matrix.read_text(encoding="utf-8"))
    generated = render(contract)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != generated:
            print(f"generated pass contract is stale: {output}")
            return 1
        print(f"generated pass contract is current: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
